### ISSUE TITLE
Getting Non-Fatal Error Message on a lot of items

### ISSUE THREAD

**Issue by ProfessorManhattan** [Rudd-O/ansible-qubes#20]
Hey, I'm trying to clean up the logging that this project outputs. I'm getting the following error but I'm unsure of how to fix it:

```
TypeError: a bytes-like object is required, not 'str'
```

This error comes from tasks that use `copy` with inline data. Here's an example:

```
- name: Save meta information about the version of AriaNG that was installed
  copy:
    dest: ~/.config/megabytelabs/ariang
    mode: 0600
    content: |
      {{ ariang_latest_release_tag.json.tag_name }}
  when: install_ariang
```
